### ISSUE TITLE
Would it be possible to change the Temp sensor to a BME280?

### ISSUE THREAD

**Issue by hairem** [mholgatem/ThermOS#20] opened 2020-06-17 14:58 UTC
I know this isn't really an issue and more of a question, but I was wanting to use a BME280 so I could get both temp and humidity values through my thermostat. I am guessing I would need to change the tempSensor.py file to fit the BME280's output to that but I wanted to know if there was anywhere else the sensor is pulled from or is it only in the part of the program? 
Just to put this out there I am not a pro at python or programming but I am trying to learn and building projects to help with that. 
Thank you for your time.

**Comment by mholgatem** [comment] 2020-06-17 17:57
so the answer is yes and no. You only need to edit tempSensor.py to send temperature data from any type of temp sensor to all parts of the program. The problem is, it is only designed to return temperature data. If you want to return and handle humidity, you are going to need to modify other parts of the code. I have plans to add support for the BME280's, but unfortunately I have had little time lately to work on my hobbies.

**Comment by hairem** [comment] 2020-06-17 18:53
Thank you for the reply, I'll try my hand at it and will be happy to share
anything I do with you if you are interested.

**Comment by mholgatem** [comment] 2020-06-17 22:38
sounds good. I'm going to close this issue, but you can still comment on it if you have further questions.

**Closed as completed by mholgatem** 2020-06-17 22:38 UTC
